auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: "2021-07-01"
      store: aws
      object_store: aws
      schema: v11
      index:
        prefix: loki_
        period: 168h

storage_config:
  aws:
    s3: s3://:@eu-west-1
    bucketnames: loki-lab
    dynamodb:
      dynamodb_url: dynamodb://:@eu-west-1

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
