---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.1.0
          ports:
            - containerPort: 3100
              name: http-loki
              protocol: TCP
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data	  
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: config
          configMap:
            name: lokicm
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
  - name: http-loki
    port: 3100
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-lb
spec:
  selector:
    app: loki
  ports:
  - name: http-loki
    port: 3100
    protocol: TCP
  type: LoadBalancer